GET http://localhost:3000/api/user
Accept: application/json

###

GET http://localhost:3000/api/user/ac8f5587-33dc-412c-9b0b-a134e7cf6f7b
Accept: application/json

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
  "name": "Frank"
}

###

PATCH http://localhost:3000/api/user/ac8f5587-33dc-412c-9b0b-a134e7cf6f7b
Content-Type: application/json

{
  "name": "Max"
}

###

DELETE http://localhost:3000/api/user/68776039-a568-49c1-9f95-68de56da0c7d
