version: "3.8"

services:
  https_proxy:
    image: docker.io/library/nginx:1.21.4-alpine
    ports:
      - 127.0.0.1:8080:80/tcp
      - 127.0.0.1:8443:443/tcp
    volumes:
      - ./https_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./https_proxy/certs:/etc/nginx/certs
