version: "3.8"

services:
  application:
    build:
      context: ./app
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    networks:
      - everything
    env_file: .env

    # We have to override the redirect url manually otherwise https_proxy
    # requests oauth2-proxy via http://application:8080 (see nginx.conf). We
    # can't use oauth2-proxy's reverse_proxy option since it doesn't use the
    # correct port
    command: --redirect-url "https://localhost:8443/oauth2/callback"

  https_proxy:
    image: docker.io/library/nginx:1.21.4-alpine
    ports:
      - 127.0.0.1:8080:80/tcp
      - 127.0.0.1:8443:443/tcp
    volumes:
      - ./https_proxy/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./https_proxy/certs:/etc/nginx/certs
    depends_on:
      - application
    networks:
      - everything

networks:
  everything:
