name: Verify Dockerfile

on:
  push:
    paths:
      - '.github/workflows/verify_dockerfile.yml'
      - 'app/next.js/**'
      - '.nvmrc'

jobs:

  verify:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
      id: buildx
      with:
        install: true

    - name: Build
      env:
        AWS_ACCESS_KEY: dummy
        AWS_SECRET_ACCESS_KEY: dummy
      run: docker build --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ./app
