name: Verify Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/verify_dockerfile.yml"
      - "app-runner-oauth2-proxy-dynamodb/app/.dockerignore"
      - "app-runner-oauth2-proxy-dynamodb/app/Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/verify_dockerfile.yml"
      - "app-runner-oauth2-proxy-dynamodb/app/.dockerignore"
      - "app-runner-oauth2-proxy-dynamodb/app/Dockerfile"

jobs:
  verify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        id: buildx
        with:
          install: true

      - name: Build
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
        run: docker build --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ./app
        working-directory: ./app-runner-oauth2-proxy-dynamodb
