name: Verify Prettier

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: ".nvmrc"

      - run: npx prettier --check .
